### ISSUE TITLE
Problem encoding the " ' " character when viewing comments

### ISSUE THREAD

**Issue by marcandregirard** [julienXX/gophsters#1]
See http://gopher.floodgap.com/gopher/gw?gopher://sdf.org:70/0/users/julienxx/Lobste.rs/znipvt.txt and you will see that currently the " ' " is not handled correctly. I tried in Chrome 65.0.3325.181 (Official Build) (64-bit) and Firefox 61.0.1 (64-bit) and both had the same issue. 

I added a screenshot if this is a locale issue. If you need more information, don't hesitate to ask :) 
![problem](https://user-images.githubusercontent.com/5870655/43281478-cb0cb566-90e1-11e8-9a7a-7e136f582f8d.png)

**Comment by julienXX** [comment]
Seems it’s a floodgap issue, when viewing it via lynx or any gopher client it’s okay. I don’t really know how to handle this :/

**Comment by marcandregirard** [comment]
Nice then, I'll try to report it to floodgap since it's not on your side!

**Comment by julienXX** [comment]
Hmm actually it looks weird too sometimes. I’ll have a look. Thanks for the heads up!

**Comment by julienXX** [comment]
I updated the code with some problematic chars replacement, this should hopefully look better.
